[project]
name = "newsletter-saas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.8.0",
    "groq>=0.31.0",
    "python-dotenv>=1.1.1",
]
